deploy:
  docker:
    - image: circleci/node:16
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: Configurar SSH para despliegue
        command: |
          mkdir -p ~/.ssh
          echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$SERVER_HOST" >> ~/.ssh/known_hosts
    - run:
        name: Verificar conexi贸n SSH
        command: ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_HOST "echo 'Conexi贸n SSH exitosa'"
    - run:
        name: Desplegar aplicaci贸n
        command: ssh $SSH_USER@$SERVER_HOST "cd /ruta/del/proyecto && git pull origin main && npm install && pm2 restart app"
    - run:
        name: Notificar despliegue exitoso
        command: |
          if [ -n "$SLACK_WEBHOOK_URL" ]; then
            curl -X POST -H 'Content-type: application/json' --data '{"text":"Despliegue exitoso en producci贸n."}' "$SLACK_WEBHOOK_URL"
          fi
