version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:16  
    working_directory: ~/repo  
    steps:
      - checkout  
      - run:
          name: Instalar dependencias
          command: npm install  
      - run:
          name: Instalar Jest globalmente
          command: sudo npm install -g jest  
      - run:
          name: Verificar instalación de Jest
          command: npx jest --version  
      - run:
          name: Ejecutar pruebas
          command: npm test 

  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Construir aplicación
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build/

  package:
    docker:
      - image: circleci/node:16
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Crear artefacto de entrega
          command: tar -czf build.tar.gz build/
      - store_artifacts:
          path: build.tar.gz

workflows:
  version: 2
  build_test_package:
    jobs:
      - test
      - build:
          requires:
            - test
      - package:
          requires:
            - build
