version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: npm install
      - run:
          name: Instalar Jest globalmente
          command: sudo npm install -g jest
      - run:
          name: Verificar instalación de Jest
          command: npx jest --version
      - run:
          name: Ejecutar pruebas
          command: npm test

  delivery:
    docker:
      - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Notificar sobre el estado del build
          command: echo "Las pruebas han pasado. Listo para entrega."
      - run:
          name: Enviar notificación (Slack, Email, etc.)
          command: |
            if [ -n "$SLACK_WEBHOOK_URL" ]; then
              curl -X POST -H 'Content-type: application/json' --data '{"text":"El build está listo para ser desplegado."}' "$SLACK_WEBHOOK_URL"
            else
              echo "SLACK_WEBHOOK_URL no está definido, omitiendo notificación."
            fi

  deploy:
    docker:
      - image: circleci/python:3.8  # Esto es un ejemplo; usa la imagen que necesites
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Desplegar aplicación
          command: |
            #!/bin/bash
            echo "Iniciando despliegue a producción..."

            # Ejemplo de comandos para desplegar a un servidor remoto via SSH
            ssh -o StrictHostKeyChecking=no user@your-server.com << 'EOF'
            cd /path/to/your/app
            git pull origin main  # Obtener la última versión de la rama principal
            npm install  # Instalar dependencias
            npm run build  # Si tienes una construcción previa
            pm2 restart app  # Reiniciar el servidor (si usas pm2)
            
            echo "Despliegue completado."

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test
      - delivery:
          requires:
            - test
      - deploy:
          requires:
            - delivery
