version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:16  
    working_directory: ~/repo  
    steps:
      - checkout  
      
      - run:
          name: Instalar dependencias
          command: npm install  

      - run:
          name: Instalar Jest globalmente
          command: sudo npm install -g jest  

      - run:
          name: Verificar instalación de Jest
          command: npx jest --version  

      - run:
          name: Ejecutar pruebas
          command: npm test 

  delivery:
    docker:
      - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - run:
          name: Notificar en Slack
          command: |
            if [ -z "$SLACK_WEBHOOK_URL" ]; then
              echo "Error: SLACK_WEBHOOK_URL no está definido"
              exit 1
            fi
            curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"✅ CI Passed! Application is ready for review."}' \
            "$SLACK_WEBHOOK_URL"

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - delivery:
          requires:
            - test