version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:16  
    working_directory: ~/repo  
    steps:
      - checkout  
      - run:
          name: Instalar dependencias
          command: npm install  
      - run:
          name: Instalar Jest globalmente
          command: sudo npm install -g jest  
      - run:
          name: Verificar instalación de Jest
          command: npx jest --version  
      - run:
          name: Ejecutar pruebas
          command: npm test 

  package:
    docker:
      - image: circleci/node:16
    steps:
      - checkout  # Asegura que el código esté disponible
      - run:
          name: Verificar archivos disponibles
          command: ls -lah
      - run:
          name: Crear artefacto de entrega
          command: sudo tar --exclude='.git' --exclude='node_modules' --ignore-failed-read -czf build.tar.gz .
      - store_artifacts:
          path: build.tar.gz

workflows:
  version: 2
  build_test_package:
    jobs:
      - test
      - package:
          requires:
            - test
